#!/bin/bash

path="/usr/local/bin/juk"

data=`rosnode list | grep JUK`

echo "Detect JUK nodes:"
num=""
num=$((num+1))
for i in $data
do
  echo "$num) $i " 
  rosnode kill $i
  num=$((num+1))
done

echo ""




C2="$path/juk_dji_core $@" 
echo "Launch $C2"
$C2 & 
P2=$!

C3="$path/juk_logger $@" 
echo "Launch $C3"
$C3 & 
P3=$!

C4="$path/EmlidPub" 
echo "Launch $C4"
$C4 & 
P4=$!



C5="$path/juk_aruco" 
echo "Launch $C5"
$C5 & 
P5=$!



C1="$path/juk_navigation_control $@" 
echo "Launch $C1"
$C1 & 
P1=$!

wait $P1 $P2 $P3 $P4 $P5

