#!/bin/bash

path="/usr/local/bin/juk"

PROC="$path/juk_aruco" 

if [[ "$1" == "--start" ]]; then
echo "~~~~START ARUCO MODULE"

$PROC & 

p=$!
wait $p 

elif [[ "$1" == "--stop" ]]; then
echo "~~~~STOP ARUCO MODULE"

rosnode kill JUK_ARUCO

fi
